/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <stdexcept>


#include <vector>
#include <stdexcept>


#include <string>



#include "LocationEngine/src/Entity/NPXBeacon.h"
#include "LocationEngine/src/Entity/NPXPoint.h"
#include "LocationEngine/src/Entity/NPXPublicBeacon.h"
#include "LocationEngine/src/Entity/NPXScannedBeacon.h"

#include "LocationEngine/src/LocationEngine/ILocationEngine.h"

using namespace std;
using namespace Nephogram::BLELocationEngine;


SWIGINTERN std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::const_reference std_vector_Sl_Nephogram_BLELocationEngine_NPXPublicBeacon_Sg__get(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_Nephogram_BLELocationEngine_NPXPublicBeacon_Sg__set(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *self,int i,std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::const_reference std_vector_Sl_Nephogram_BLELocationEngine_NPXScannedBeacon_SS_const_Sm__Sg__get(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_Nephogram_BLELocationEngine_NPXScannedBeacon_SS_const_Sm__Sg__set(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *self,int i,std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXBeacon_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::NPXBeacon *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Nephogram::BLELocationEngine::NPXBeacon *)new Nephogram::BLELocationEngine::NPXBeacon();
  *(Nephogram::BLELocationEngine::NPXBeacon **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXBeacon_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  uint16_t arg2 ;
  uint16_t arg3 ;
  Nephogram::BLELocationEngine::NPXBeacon *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (uint16_t)jarg2; 
  arg3 = (uint16_t)jarg3; 
  result = (Nephogram::BLELocationEngine::NPXBeacon *)new Nephogram::BLELocationEngine::NPXBeacon((char const *)arg1,arg2,arg3);
  *(Nephogram::BLELocationEngine::NPXBeacon **)&jresult = result; 
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1NPXBeacon(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Nephogram::BLELocationEngine::NPXBeacon *arg1 = (Nephogram::BLELocationEngine::NPXBeacon *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Nephogram::BLELocationEngine::NPXBeacon **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXBeacon_1getMajor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Nephogram::BLELocationEngine::NPXBeacon *arg1 = (Nephogram::BLELocationEngine::NPXBeacon *) 0 ;
  uint16_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXBeacon **)&jarg1; 
  result = (uint16_t)((Nephogram::BLELocationEngine::NPXBeacon const *)arg1)->getMajor();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXBeacon_1getMinor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Nephogram::BLELocationEngine::NPXBeacon *arg1 = (Nephogram::BLELocationEngine::NPXBeacon *) 0 ;
  uint16_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXBeacon **)&jarg1; 
  result = (uint16_t)((Nephogram::BLELocationEngine::NPXBeacon const *)arg1)->getMinor();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXBeacon_1getUuid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Nephogram::BLELocationEngine::NPXBeacon *arg1 = (Nephogram::BLELocationEngine::NPXBeacon *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXBeacon **)&jarg1; 
  result = ((Nephogram::BLELocationEngine::NPXBeacon const *)arg1)->getUuid();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_hash_1beacon_1key_1hash_1beacon_1key(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::hash_beacon_key *arg1 = (Nephogram::BLELocationEngine::hash_beacon_key *) 0 ;
  Nephogram::BLELocationEngine::NPXBeacon *arg2 = 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::hash_beacon_key **)&jarg1; 
  arg2 = *(Nephogram::BLELocationEngine::NPXBeacon **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXBeacon const & reference is null");
    return 0;
  } 
  result = ((Nephogram::BLELocationEngine::hash_beacon_key const *)arg1)->operator ()((Nephogram::BLELocationEngine::NPXBeacon const &)*arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1hash_1beacon_1key(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Nephogram::BLELocationEngine::hash_beacon_key *arg1 = (Nephogram::BLELocationEngine::hash_beacon_key *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Nephogram::BLELocationEngine::hash_beacon_key **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jboolean JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_equal_1beacon_1key_1equal_1beacon_1key(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jobject jarg3_) {
  jboolean jresult = 0 ;
  Nephogram::BLELocationEngine::equal_beacon_key *arg1 = (Nephogram::BLELocationEngine::equal_beacon_key *) 0 ;
  Nephogram::BLELocationEngine::NPXBeacon *arg2 = 0 ;
  Nephogram::BLELocationEngine::NPXBeacon *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg3_;
  arg1 = *(Nephogram::BLELocationEngine::equal_beacon_key **)&jarg1; 
  arg2 = *(Nephogram::BLELocationEngine::NPXBeacon **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXBeacon const & reference is null");
    return 0;
  } 
  arg3 = *(Nephogram::BLELocationEngine::NPXBeacon **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXBeacon const & reference is null");
    return 0;
  } 
  result = (bool)((Nephogram::BLELocationEngine::equal_beacon_key const *)arg1)->operator ()((Nephogram::BLELocationEngine::NPXBeacon const &)*arg2,(Nephogram::BLELocationEngine::NPXBeacon const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1equal_1beacon_1key(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Nephogram::BLELocationEngine::equal_beacon_key *arg1 = (Nephogram::BLELocationEngine::equal_beacon_key *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Nephogram::BLELocationEngine::equal_beacon_key **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXPublicBeacon_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPublicBeacon *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Nephogram::BLELocationEngine::NPXPublicBeacon *)new Nephogram::BLELocationEngine::NPXPublicBeacon();
  *(Nephogram::BLELocationEngine::NPXPublicBeacon **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXPublicBeacon_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  uint16_t arg2 ;
  uint16_t arg3 ;
  Nephogram::BLELocationEngine::NPXPoint *arg4 = 0 ;
  Nephogram::BLELocationEngine::NPXPublicBeacon *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (uint16_t)jarg2; 
  arg3 = (uint16_t)jarg3; 
  arg4 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg4;
  if (!arg4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint & reference is null");
    return 0;
  } 
  result = (Nephogram::BLELocationEngine::NPXPublicBeacon *)new Nephogram::BLELocationEngine::NPXPublicBeacon((char const *)arg1,arg2,arg3,*arg4);
  *(Nephogram::BLELocationEngine::NPXPublicBeacon **)&jresult = result; 
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1NPXPublicBeacon(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Nephogram::BLELocationEngine::NPXPublicBeacon *arg1 = (Nephogram::BLELocationEngine::NPXPublicBeacon *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Nephogram::BLELocationEngine::NPXPublicBeacon **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPublicBeacon_1getLocation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPublicBeacon *arg1 = (Nephogram::BLELocationEngine::NPXPublicBeacon *) 0 ;
  Nephogram::BLELocationEngine::NPXPoint result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPublicBeacon **)&jarg1; 
  result = ((Nephogram::BLELocationEngine::NPXPublicBeacon const *)arg1)->getLocation();
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = new Nephogram::BLELocationEngine::NPXPoint((const Nephogram::BLELocationEngine::NPXPoint &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPublicBeacon_1setLocation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Nephogram::BLELocationEngine::NPXPublicBeacon *arg1 = (Nephogram::BLELocationEngine::NPXPublicBeacon *) 0 ;
  Nephogram::BLELocationEngine::NPXPoint arg2 ;
  Nephogram::BLELocationEngine::NPXPoint *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPublicBeacon **)&jarg1; 
  argp2 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Nephogram::BLELocationEngine::NPXPoint");
    return ;
  }
  arg2 = *argp2; 
  (arg1)->setLocation(arg2);
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXPoint_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Nephogram::BLELocationEngine::NPXPoint *)new Nephogram::BLELocationEngine::NPXPoint();
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXPoint_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jdouble jarg1, jdouble jarg2) {
  jlong jresult = 0 ;
  double arg1 ;
  double arg2 ;
  Nephogram::BLELocationEngine::NPXPoint *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  arg2 = (double)jarg2; 
  result = (Nephogram::BLELocationEngine::NPXPoint *)new Nephogram::BLELocationEngine::NPXPoint(arg1,arg2);
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXPoint_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jdouble jarg1, jdouble jarg2, jint jarg3) {
  jlong jresult = 0 ;
  double arg1 ;
  double arg2 ;
  int arg3 ;
  Nephogram::BLELocationEngine::NPXPoint *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  arg2 = (double)jarg2; 
  arg3 = (int)jarg3; 
  result = (Nephogram::BLELocationEngine::NPXPoint *)new Nephogram::BLELocationEngine::NPXPoint(arg1,arg2,arg3);
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXPoint_1_1SWIG_13(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint const & reference is null");
    return 0;
  } 
  result = (Nephogram::BLELocationEngine::NPXPoint *)new Nephogram::BLELocationEngine::NPXPoint((Nephogram::BLELocationEngine::NPXPoint const &)*arg1);
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1assignment_1point(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg2 = 0 ;
  Nephogram::BLELocationEngine::NPXPoint result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  arg2 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint const & reference is null");
    return 0;
  } 
  result = (arg1)->operator =((Nephogram::BLELocationEngine::NPXPoint const &)*arg2);
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = new Nephogram::BLELocationEngine::NPXPoint((const Nephogram::BLELocationEngine::NPXPoint &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1NPXPoint(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1getFloor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  result = (int)((Nephogram::BLELocationEngine::NPXPoint const *)arg1)->getFloor();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1setFloor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->setFloor(arg2);
}


SWIGEXPORT jdouble JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1getX(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  result = (double)((Nephogram::BLELocationEngine::NPXPoint const *)arg1)->getX();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1getY(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  result = (double)((Nephogram::BLELocationEngine::NPXPoint const *)arg1)->getY();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1DistanceBetween(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg2 = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint const & reference is null");
    return 0;
  } 
  arg2 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint const & reference is null");
    return 0;
  } 
  result = (double)Nephogram::BLELocationEngine::NPXPoint::DistanceBetween((Nephogram::BLELocationEngine::NPXPoint const &)*arg1,(Nephogram::BLELocationEngine::NPXPoint const &)*arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1distanceBetween(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg2 = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  arg2 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint const & reference is null");
    return 0;
  } 
  result = (double)(arg1)->distanceBetween((Nephogram::BLELocationEngine::NPXPoint const &)*arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1equal_1point(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  arg2 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint const & reference is null");
    return 0;
  } 
  result = (bool)(arg1)->operator ==((Nephogram::BLELocationEngine::NPXPoint const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPoint_1not_1equal_1point(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  Nephogram::BLELocationEngine::NPXPoint *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  arg2 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Nephogram::BLELocationEngine::NPXPoint const & reference is null");
    return 0;
  } 
  result = (bool)(arg1)->operator !=((Nephogram::BLELocationEngine::NPXPoint const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_INVALID_1POINT_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Nephogram::BLELocationEngine::NPXPoint *arg1 = (Nephogram::BLELocationEngine::NPXPoint *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXPoint **)&jarg1; 
  Nephogram::BLELocationEngine::INVALID_POINT = *arg1;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_INVALID_1POINT_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::NPXPoint *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Nephogram::BLELocationEngine::NPXPoint *)&Nephogram::BLELocationEngine::INVALID_POINT;
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXProximityUnknwon_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  Nephogram::BLELocationEngine::NPXProximity result;
  
  (void)jenv;
  (void)jcls;
  result = (Nephogram::BLELocationEngine::NPXProximity)Nephogram::BLELocationEngine::NPXProximityUnknwon;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1NPXScannedBeacon(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jint jarg3, jint jarg4, jdouble jarg5, jint jarg6) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  uint16_t arg2 ;
  uint16_t arg3 ;
  int arg4 ;
  double arg5 ;
  Nephogram::BLELocationEngine::NPXProximity arg6 ;
  Nephogram::BLELocationEngine::NPXScannedBeacon *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (uint16_t)jarg2; 
  arg3 = (uint16_t)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (double)jarg5; 
  arg6 = (Nephogram::BLELocationEngine::NPXProximity)jarg6; 
  result = (Nephogram::BLELocationEngine::NPXScannedBeacon *)new Nephogram::BLELocationEngine::NPXScannedBeacon((char const *)arg1,arg2,arg3,arg4,arg5,arg6);
  *(Nephogram::BLELocationEngine::NPXScannedBeacon **)&jresult = result; 
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1NPXScannedBeacon(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Nephogram::BLELocationEngine::NPXScannedBeacon *arg1 = (Nephogram::BLELocationEngine::NPXScannedBeacon *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Nephogram::BLELocationEngine::NPXScannedBeacon **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXScannedBeacon_1getRssi(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Nephogram::BLELocationEngine::NPXScannedBeacon *arg1 = (Nephogram::BLELocationEngine::NPXScannedBeacon *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXScannedBeacon **)&jarg1; 
  result = (int)((Nephogram::BLELocationEngine::NPXScannedBeacon const *)arg1)->getRssi();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXScannedBeacon_1getAccuracy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Nephogram::BLELocationEngine::NPXScannedBeacon *arg1 = (Nephogram::BLELocationEngine::NPXScannedBeacon *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXScannedBeacon **)&jarg1; 
  result = (double)((Nephogram::BLELocationEngine::NPXScannedBeacon const *)arg1)->getAccuracy();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXScannedBeacon_1getProximity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Nephogram::BLELocationEngine::NPXScannedBeacon *arg1 = (Nephogram::BLELocationEngine::NPXScannedBeacon *) 0 ;
  Nephogram::BLELocationEngine::NPXProximity result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::NPXScannedBeacon **)&jarg1; 
  result = (Nephogram::BLELocationEngine::NPXProximity)((Nephogram::BLELocationEngine::NPXScannedBeacon const *)arg1)->getProximity();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1VectorOfPublicBeacon_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *)new std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >();
  *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1VectorOfPublicBeacon_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::size_type arg1 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::size_type)jarg1; 
  result = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *)new std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >(arg1);
  *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  result = ((std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  result = ((std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  arg2 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  result = (bool)((std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  arg2 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type const & reference is null");
    return ;
  } 
  (arg1)->push_back((std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  int arg2 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type *) &std_vector_Sl_Nephogram_BLELocationEngine_NPXPublicBeacon_Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfPublicBeacon_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  int arg2 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon >::value_type const & reference is null");
    return ;
  } 
  try {
    std_vector_Sl_Nephogram_BLELocationEngine_NPXPublicBeacon_Sg__set(arg1,arg2,(Nephogram::BLELocationEngine::NPXPublicBeacon const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1VectorOfPublicBeacon(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1VectorOfScannedBeaconPointer_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *)new std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >();
  *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_new_1VectorOfScannedBeaconPointer_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::size_type arg1 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::size_type)jarg1; 
  result = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *)new std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >(arg1);
  *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  result = ((std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  result = ((std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  arg2 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  result = (bool)((std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *arg2 = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type temp2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  temp2 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *)&jarg2;
  arg2 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *)&temp2; 
  (arg1)->push_back((std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  int arg2 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *) &std_vector_Sl_Nephogram_BLELocationEngine_NPXScannedBeacon_SS_const_Sm__Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *)&jresult = *result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_VectorOfScannedBeaconPointer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  int arg2 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *arg3 = 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type temp3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  arg2 = (int)jarg2; 
  temp3 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *)&jarg3;
  arg3 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * >::value_type *)&temp3; 
  try {
    std_vector_Sl_Nephogram_BLELocationEngine_NPXScannedBeacon_SS_const_Sm__Sg__set(arg1,arg2,(Nephogram::BLELocationEngine::NPXScannedBeacon const *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1VectorOfScannedBeaconPointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg1 = (std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_ILocationEngine_1Initilize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Nephogram::BLELocationEngine::ILocationEngine *arg1 = (Nephogram::BLELocationEngine::ILocationEngine *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::ILocationEngine **)&jarg1; 
  arg2 = *(std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > const & reference is null");
    return ;
  } 
  (arg1)->Initilize((std::vector< Nephogram::BLELocationEngine::NPXPublicBeacon > const &)*arg2);
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_ILocationEngine_1processBeacons(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Nephogram::BLELocationEngine::ILocationEngine *arg1 = (Nephogram::BLELocationEngine::ILocationEngine *) 0 ;
  std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Nephogram::BLELocationEngine::ILocationEngine **)&jarg1; 
  arg2 = *(std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< Nephogram::BLELocationEngine::NPXScannedBeacon const * > & reference is null");
    return ;
  } 
  (arg1)->processBeacons(*arg2);
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_ILocationEngine_1addStepEvent(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Nephogram::BLELocationEngine::ILocationEngine *arg1 = (Nephogram::BLELocationEngine::ILocationEngine *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::ILocationEngine **)&jarg1; 
  (arg1)->addStepEvent();
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_ILocationEngine_1getLocation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Nephogram::BLELocationEngine::ILocationEngine *arg1 = (Nephogram::BLELocationEngine::ILocationEngine *) 0 ;
  Nephogram::BLELocationEngine::NPXPoint result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Nephogram::BLELocationEngine::ILocationEngine **)&jarg1; 
  result = ((Nephogram::BLELocationEngine::ILocationEngine const *)arg1)->getLocation();
  *(Nephogram::BLELocationEngine::NPXPoint **)&jresult = new Nephogram::BLELocationEngine::NPXPoint((const Nephogram::BLELocationEngine::NPXPoint &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_delete_1ILocationEngine(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Nephogram::BLELocationEngine::ILocationEngine *arg1 = (Nephogram::BLELocationEngine::ILocationEngine *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Nephogram::BLELocationEngine::ILocationEngine **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_CreateNPXStepBaseTriangulationEngine(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  NPXAlgorithmType arg1 ;
  Nephogram::BLELocationEngine::ILocationEngine *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (NPXAlgorithmType)jarg1; 
  result = (Nephogram::BLELocationEngine::ILocationEngine *)CreateNPXStepBaseTriangulationEngine(arg1);
  *(Nephogram::BLELocationEngine::ILocationEngine **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXPublicBeacon_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(Nephogram::BLELocationEngine::NPXBeacon **)&baseptr = *(Nephogram::BLELocationEngine::NPXPublicBeacon **)&jarg1;
    return baseptr;
}

SWIGEXPORT jlong JNICALL Java_cn_nephogram_locationengine_swig_BLELocationEngineJNI_NPXScannedBeacon_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(Nephogram::BLELocationEngine::NPXBeacon **)&baseptr = *(Nephogram::BLELocationEngine::NPXScannedBeacon **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

