/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class equal_beacon_key {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected equal_beacon_key(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(equal_beacon_key obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TYLocationEngineJNI.delete_equal_beacon_key(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean EqualBeaconKey(IPXBeacon key1, IPXBeacon key2) {
    return TYLocationEngineJNI.equal_beacon_key_EqualBeaconKey(swigCPtr, this, IPXBeacon.getCPtr(key1), key1, IPXBeacon.getCPtr(key2), key2);
  }

  public equal_beacon_key() {
    this(TYLocationEngineJNI.new_equal_beacon_key(), true);
  }

}
