/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class ILocationEngine {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ILocationEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ILocationEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TYLocationEngineJNI.delete_ILocationEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Initilize(VectorOfPublicBeacon beacons, String checkCode) {
    TYLocationEngineJNI.ILocationEngine_Initilize(swigCPtr, this, VectorOfPublicBeacon.getCPtr(beacons), beacons, checkCode);
  }

  public void processBeacons(VectorOfScannedBeaconPointer beacons) {
    TYLocationEngineJNI.ILocationEngine_processBeacons(swigCPtr, this, VectorOfScannedBeaconPointer.getCPtr(beacons), beacons);
  }

  public void addStepEvent() {
    TYLocationEngineJNI.ILocationEngine_addStepEvent(swigCPtr, this);
  }

  public void reset() {
    TYLocationEngineJNI.ILocationEngine_reset(swigCPtr, this);
  }

  public IPXPoint getLocation() {
    return new IPXPoint(TYLocationEngineJNI.ILocationEngine_getLocation(swigCPtr, this), true);
  }

}
