/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public enum IPXAlgorithmType {
	IPXSingle, IPXTripple, IPXHybridSingle, IPXHybridTripple, IPXLinearWeighting, IPXQuadraticWeighting;

	public final int swigValue() {
		return swigValue;
	}

	public static IPXAlgorithmType swigToEnum(int swigValue) {
		IPXAlgorithmType[] swigValues = IPXAlgorithmType.class
				.getEnumConstants();
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (IPXAlgorithmType swigEnum : swigValues)
			if (swigEnum.swigValue == swigValue)
				return swigEnum;
		throw new IllegalArgumentException("No enum " + IPXAlgorithmType.class
				+ " with value " + swigValue);
	}

	private IPXAlgorithmType() {
		this.swigValue = SwigNext.next++;
	}

	private IPXAlgorithmType(int swigValue) {
		this.swigValue = swigValue;
		SwigNext.next = swigValue + 1;
	}

	private IPXAlgorithmType(IPXAlgorithmType swigEnum) {
		this.swigValue = swigEnum.swigValue;
		SwigNext.next = this.swigValue + 1;
	}

	private final int swigValue;

	private static class SwigNext {
		private static int next = 0;
	}
}
