/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class IPXPublicBeacon extends IPXBeacon {
  private long swigCPtr;

  protected IPXPublicBeacon(long cPtr, boolean cMemoryOwn) {
    super(TYLocationEngineJNI.IPXPublicBeacon_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXPublicBeacon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TYLocationEngineJNI.delete_IPXPublicBeacon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IPXPublicBeacon() {
    this(TYLocationEngineJNI.new_IPXPublicBeacon__SWIG_0(), true);
  }

  public IPXPublicBeacon(String uuid, int major, int minor, IPXPoint location) {
    this(TYLocationEngineJNI.new_IPXPublicBeacon__SWIG_1(uuid, major, minor, IPXPoint.getCPtr(location), location), true);
  }

  public IPXPoint getLocation() {
    return new IPXPoint(TYLocationEngineJNI.IPXPublicBeacon_getLocation(swigCPtr, this), true);
  }

  public void setLocation(IPXPoint lp) {
    TYLocationEngineJNI.IPXPublicBeacon_setLocation(swigCPtr, this, IPXPoint.getCPtr(lp), lp);
  }

}
