/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class IPXPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPXPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TYLocationEngineJNI.delete_IPXPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IPXPoint() {
    this(TYLocationEngineJNI.new_IPXPoint__SWIG_0(), true);
  }

  public IPXPoint(double px, double py) {
    this(TYLocationEngineJNI.new_IPXPoint__SWIG_1(px, py), true);
  }

  public IPXPoint(double px, double py, int pf) {
    this(TYLocationEngineJNI.new_IPXPoint__SWIG_2(px, py, pf), true);
  }

  public IPXPoint(IPXPoint p) {
    this(TYLocationEngineJNI.new_IPXPoint__SWIG_3(IPXPoint.getCPtr(p), p), true);
  }

  public IPXPoint assignment_point(IPXPoint p) {
    return new IPXPoint(TYLocationEngineJNI.IPXPoint_assignment_point(swigCPtr, this, IPXPoint.getCPtr(p), p), true);
  }

  public int getFloor() {
    return TYLocationEngineJNI.IPXPoint_getFloor(swigCPtr, this);
  }

  public void setFloor(int floor) {
    TYLocationEngineJNI.IPXPoint_setFloor(swigCPtr, this, floor);
  }

  public double getX() {
    return TYLocationEngineJNI.IPXPoint_getX(swigCPtr, this);
  }

  public double getY() {
    return TYLocationEngineJNI.IPXPoint_getY(swigCPtr, this);
  }

  public static double DistanceBetween(IPXPoint p1, IPXPoint p2) {
    return TYLocationEngineJNI.IPXPoint_DistanceBetween(IPXPoint.getCPtr(p1), p1, IPXPoint.getCPtr(p2), p2);
  }

  public double distanceBetween(IPXPoint p2) {
    return TYLocationEngineJNI.IPXPoint_distanceBetween(swigCPtr, this, IPXPoint.getCPtr(p2), p2);
  }

  public boolean equal_point(IPXPoint aPoint) {
    return TYLocationEngineJNI.IPXPoint_equal_point(swigCPtr, this, IPXPoint.getCPtr(aPoint), aPoint);
  }

  public boolean not_equal_point(IPXPoint aPoint) {
    return TYLocationEngineJNI.IPXPoint_not_equal_point(swigCPtr, this, IPXPoint.getCPtr(aPoint), aPoint);
  }

}
