/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class IPXScannedBeacon extends IPXBeacon {
  private long swigCPtr;

  protected IPXScannedBeacon(long cPtr, boolean cMemoryOwn) {
    super(TYLocationEngineJNI.IPXScannedBeacon_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXScannedBeacon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TYLocationEngineJNI.delete_IPXScannedBeacon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IPXScannedBeacon(String uuid, int major, int minor, int rssi, double accuracy, IPXProximity proximity) {
    this(TYLocationEngineJNI.new_IPXScannedBeacon(uuid, major, minor, rssi, accuracy, proximity.swigValue()), true);
  }

  public int getRssi() {
    return TYLocationEngineJNI.IPXScannedBeacon_getRssi(swigCPtr, this);
  }

  public double getAccuracy() {
    return TYLocationEngineJNI.IPXScannedBeacon_getAccuracy(swigCPtr, this);
  }

  public IPXProximity getProximity() {
    return IPXProximity.swigToEnum(TYLocationEngineJNI.IPXScannedBeacon_getProximity(swigCPtr, this));
  }

}
