/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class TYLocationEngine {
  public static void setINVALID_POINT(IPXPoint value) {
    TYLocationEngineJNI.INVALID_POINT_set(IPXPoint.getCPtr(value), value);
  }

  public static IPXPoint getINVALID_POINT() {
    long cPtr = TYLocationEngineJNI.INVALID_POINT_get();
    return (cPtr == 0) ? null : new IPXPoint(cPtr, false);
  }

  public static ILocationEngine CreateIPXStepBaseTriangulationEngine(IPXAlgorithmType type) {
    long cPtr = TYLocationEngineJNI.CreateIPXStepBaseTriangulationEngine(type.swigValue());
    return (cPtr == 0) ? null : new ILocationEngine(cPtr, false);
  }

}
