/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class VectorOfPublicBeacon {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfPublicBeacon(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfPublicBeacon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TYLocationEngineJNI.delete_VectorOfPublicBeacon(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfPublicBeacon() {
    this(TYLocationEngineJNI.new_VectorOfPublicBeacon__SWIG_0(), true);
  }

  public VectorOfPublicBeacon(long n) {
    this(TYLocationEngineJNI.new_VectorOfPublicBeacon__SWIG_1(n), true);
  }

  public long size() {
    return TYLocationEngineJNI.VectorOfPublicBeacon_size(swigCPtr, this);
  }

  public long capacity() {
    return TYLocationEngineJNI.VectorOfPublicBeacon_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    TYLocationEngineJNI.VectorOfPublicBeacon_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return TYLocationEngineJNI.VectorOfPublicBeacon_isEmpty(swigCPtr, this);
  }

  public void clear() {
    TYLocationEngineJNI.VectorOfPublicBeacon_clear(swigCPtr, this);
  }

  public void add(IPXPublicBeacon x) {
    TYLocationEngineJNI.VectorOfPublicBeacon_add(swigCPtr, this, IPXPublicBeacon.getCPtr(x), x);
  }

  public IPXPublicBeacon get(int i) {
    return new IPXPublicBeacon(TYLocationEngineJNI.VectorOfPublicBeacon_get(swigCPtr, this, i), false);
  }

  public void set(int i, IPXPublicBeacon val) {
    TYLocationEngineJNI.VectorOfPublicBeacon_set(swigCPtr, this, i, IPXPublicBeacon.getCPtr(val), val);
  }

}
