/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.locationengine.swig;

public class VectorOfScannedBeaconPointer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfScannedBeaconPointer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfScannedBeaconPointer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TYLocationEngineJNI.delete_VectorOfScannedBeaconPointer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfScannedBeaconPointer() {
    this(TYLocationEngineJNI.new_VectorOfScannedBeaconPointer__SWIG_0(), true);
  }

  public VectorOfScannedBeaconPointer(long n) {
    this(TYLocationEngineJNI.new_VectorOfScannedBeaconPointer__SWIG_1(n), true);
  }

  public long size() {
    return TYLocationEngineJNI.VectorOfScannedBeaconPointer_size(swigCPtr, this);
  }

  public long capacity() {
    return TYLocationEngineJNI.VectorOfScannedBeaconPointer_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    TYLocationEngineJNI.VectorOfScannedBeaconPointer_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return TYLocationEngineJNI.VectorOfScannedBeaconPointer_isEmpty(swigCPtr, this);
  }

  public void clear() {
    TYLocationEngineJNI.VectorOfScannedBeaconPointer_clear(swigCPtr, this);
  }

  public void add(IPXScannedBeacon x) {
    TYLocationEngineJNI.VectorOfScannedBeaconPointer_add(swigCPtr, this, IPXScannedBeacon.getCPtr(x), x);
  }

  public IPXScannedBeacon get(int i) {
    long cPtr = TYLocationEngineJNI.VectorOfScannedBeaconPointer_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new IPXScannedBeacon(cPtr, false);
  }

  public void set(int i, IPXScannedBeacon val) {
    TYLocationEngineJNI.VectorOfScannedBeaconPointer_set(swigCPtr, this, i, IPXScannedBeacon.getCPtr(val), val);
  }

}
