/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.nephogram.locationengine.swig;

public class BLELocationEngine {
  public static void setINVALID_POINT(NPXPoint value) {
    BLELocationEngineJNI.INVALID_POINT_set(NPXPoint.getCPtr(value), value);
  }

  public static NPXPoint getINVALID_POINT() {
    long cPtr = BLELocationEngineJNI.INVALID_POINT_get();
    return (cPtr == 0) ? null : new NPXPoint(cPtr, false);
  }

  public static ILocationEngine CreateNPXStepBaseTriangulationEngine(NPXAlgorithmType type) {
    long cPtr = BLELocationEngineJNI.CreateNPXStepBaseTriangulationEngine(type.swigValue());
    return (cPtr == 0) ? null : new ILocationEngine(cPtr, false);
  }

}
