/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.nephogram.locationengine.swig;

public class equal_beacon_key {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected equal_beacon_key(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(equal_beacon_key obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BLELocationEngineJNI.delete_equal_beacon_key(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equal_beacon_key(NPXBeacon key1, NPXBeacon key2) {
    return BLELocationEngineJNI.equal_beacon_key_equal_beacon_key(swigCPtr, this, NPXBeacon.getCPtr(key1), key1, NPXBeacon.getCPtr(key2), key2);
  }

}
