/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.nephogram.locationengine.swig;

public class hash_beacon_key {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected hash_beacon_key(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(hash_beacon_key obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BLELocationEngineJNI.delete_hash_beacon_key(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long hash_beacon_key(NPXBeacon key) {
    return BLELocationEngineJNI.hash_beacon_key_hash_beacon_key(swigCPtr, this, NPXBeacon.getCPtr(key), key);
  }

}
