/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.nephogram.locationengine.swig;

public class NPXBeacon {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NPXBeacon(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NPXBeacon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BLELocationEngineJNI.delete_NPXBeacon(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NPXBeacon() {
    this(BLELocationEngineJNI.new_NPXBeacon__SWIG_0(), true);
  }

  public NPXBeacon(String uuid, int major, int minor) {
    this(BLELocationEngineJNI.new_NPXBeacon__SWIG_1(uuid, major, minor), true);
  }

  public int getMajor() {
    return BLELocationEngineJNI.NPXBeacon_getMajor(swigCPtr, this);
  }

  public int getMinor() {
    return BLELocationEngineJNI.NPXBeacon_getMinor(swigCPtr, this);
  }

  public String getUuid() {
    return BLELocationEngineJNI.NPXBeacon_getUuid(swigCPtr, this);
  }

}
