/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.nephogram.locationengine.swig;

public class NPXPublicBeacon extends NPXBeacon {
  private long swigCPtr;

  protected NPXPublicBeacon(long cPtr, boolean cMemoryOwn) {
    super(BLELocationEngineJNI.NPXPublicBeacon_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NPXPublicBeacon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BLELocationEngineJNI.delete_NPXPublicBeacon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NPXPublicBeacon() {
    this(BLELocationEngineJNI.new_NPXPublicBeacon__SWIG_0(), true);
  }

  public NPXPublicBeacon(String uuid, int major, int minor, NPXPoint location) {
    this(BLELocationEngineJNI.new_NPXPublicBeacon__SWIG_1(uuid, major, minor, NPXPoint.getCPtr(location), location), true);
  }

  public NPXPoint getLocation() {
    return new NPXPoint(BLELocationEngineJNI.NPXPublicBeacon_getLocation(swigCPtr, this), true);
  }

  public void setLocation(NPXPoint lp) {
    BLELocationEngineJNI.NPXPublicBeacon_setLocation(swigCPtr, this, NPXPoint.getCPtr(lp), lp);
  }

}
