/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.nephogram.locationengine.swig;

public enum NPXProximity {
  NPXProximityUnknwon(BLELocationEngineJNI.NPXProximityUnknwon_get()),
  NPXProximityImmediate,
  NPXProximityNear,
  NPXProximityFar;

  public final int swigValue() {
    return swigValue;
  }

  public static NPXProximity swigToEnum(int swigValue) {
    NPXProximity[] swigValues = NPXProximity.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (NPXProximity swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + NPXProximity.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private NPXProximity() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private NPXProximity(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private NPXProximity(NPXProximity swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

