/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.nephogram.locationengine.swig;

public class NPXScannedBeacon extends NPXBeacon {
  private long swigCPtr;

  protected NPXScannedBeacon(long cPtr, boolean cMemoryOwn) {
    super(BLELocationEngineJNI.NPXScannedBeacon_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NPXScannedBeacon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BLELocationEngineJNI.delete_NPXScannedBeacon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NPXScannedBeacon(String uuid, int major, int minor, int rssi, double accuracy, NPXProximity proximity) {
    this(BLELocationEngineJNI.new_NPXScannedBeacon(uuid, major, minor, rssi, accuracy, proximity.swigValue()), true);
  }

  public int getRssi() {
    return BLELocationEngineJNI.NPXScannedBeacon_getRssi(swigCPtr, this);
  }

  public double getAccuracy() {
    return BLELocationEngineJNI.NPXScannedBeacon_getAccuracy(swigCPtr, this);
  }

  public NPXProximity getProximity() {
    return NPXProximity.swigToEnum(BLELocationEngineJNI.NPXScannedBeacon_getProximity(swigCPtr, this));
  }

}
